source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal "tmux-256color"
set-option -g automatic-rename off
set-option -g pane-active-border-style "fg=white"
# set-option -g terminal-overrides ',xterm-256color:RGB'
set -ga terminal-overrides ",*:Tc"


# Color Pallete - Kanagawa
# %hidden COLOR1="#8ca5b2"
# %hidden COLOR2="#191724"
# %hidden COLOR3="#ffffff"

# Color Pallete - Reverse Void
# %hidden COLOR1="#000000"
# %hidden COLOR2="#ffffff"
# %hidden COLOR3="#000000"

# Color Pallete - Vague
# %hidden COLOR1="#90a0b5"
# %hidden COLOR2="#000000"
# %hidden COLOR3="#ffffff"

# Color Pallete - Lackluster
# %hidden COLOR1="#7788AA"
# %hidden COLOR2="#000000"
# %hidden COLOR3="#aaaaaa"

# Color Pallete - Immortal
%hidden COLOR1="#7799BB"
%hidden COLOR2="#000000"
%hidden COLOR3="#aaaaaa"

# Tmux Custom Theme
# set-option -g status-style fg=$COLOR3,bold
# set-option -g status-right ""
# set-option -g status-left "#[fg=$COLOR1,bg=default]#[fg=$COLOR2,bg=$COLOR1,bold] #S #[fg=$COLOR1,bg=default,nobold]#[default]"
# set-option -g status-right "#[fg=$COLOR1,bg=default]#[fg=$COLOR2,bg=$COLOR1,bold] %H:%M #[fg=$COLOR1,bg=default,nobold]#[default]"
# set-option -g status-left-length 30
# set-option -g window-status-current-format "#[fg=$COLOR1,bg=default]#[fg=$COLOR2,bg=$COLOR1,bold] #I:#W #[fg=$COLOR1,bg=default,nobold]#[default]"
set-option -g window-status-format " #W "
set-option -g window-status-current-format " [#[fg=#c4746e]#W#[default]] "
set-option -g status-right " %H:%M "
set-option -g status-style bg=default
set -g status-justify "absolute-centre"
# set -g status-justify centre
set -g status-left-length 99
set -g status-right-length 99
set -g focus-events on


set -g status on
set -g prefix ^A
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position bottom
set -g default-terminal "${TERM}"
set -g mouse on
setw -g mode-keys vi
set-hook -g window-linked 'run-shell "~/dotfiles/scripts/autoname.sh #{session_name} #{window_index} #{window_id}"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'
set -g @resurrect-strategy-nvim 'session'
set -g @thumbs-command 'echo -n {} | pbcopy'  # macOS

run '~/.tmux/plugins/tpm/tpm'
