unbind-key -a
# bind ^X lock-server
# bind c new-window -c "$HOME"
bind c new-window -c "#{pane_current_path}"
# bind a attach-session -t "architecture"
# bind m attach-session -t "malware"
# bind d attach-session -t "dotfiles"
# bind i attach-session -t "ice"
# bind r attach-session -t "radware"
# bind o attach-session -t "kernel"
# bind b attach-session -t "blockchain"
bind / detach
bind * list-clients
bind ] switch-client -n
bind [ switch-client -p


bind p previous-window
bind n next-window

# bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
# bind ^J last-window
bind ^K list-windows
#bind w
bind z resize-pane -Z
bind ^L refresh-client
# bind l refresh-client
# bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind X kill-pane
bind x swap-pane -D
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key "^;" display-popup -h 40% -w 40% -E -b rounded "sesh picker -i -t"
bind-key ";" run-shell "sesh connect \"$(
  sesh list -H -t -c --icons | fzf-tmux -p 80%,80% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~/dev)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {3..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --no-hscroll \
    --preview-window 'right:50%:border-left' \
    --preview 'sesh preview {}' \
    --color 'preview-bg:-1,preview-fg:#cdcdcd,border:#606079,label:#aeaed1,prompt:#b4d4cf,pointer:#f3be7c,hl:#d8647e,hl+:#d8647e,bg+:#1e1e22,fg+:#cdcdcd' # Vague
    # --color 'preview-bg:-1,preview-fg:#1F1F1F,border:#5E6F8E,label:#4C465D,prompt:#D73A49,pointer:#D73A49,hl:#D73A49,hl+:#7A2E2E,bg+:#B2B2B3,fg+:#1F1F1F' # Reverse_void
)\""
