# Foreground: E0E0E0
# Selection: 2A2A2A
# Comment: 555555
# Red: E67E80
# Orange: F0BC6E
# Yellow: F0BC6E
# Green: 7A9E6E
# Purple: 9E9EC8
# Cyan: 6E9AB5
# Pink: B87A9E
fish_color_normal E0E0E0
fish_color_command 6E9AB5
fish_color_keyword B87A9E
fish_color_quote F0BC6E
fish_color_redirection E0E0E0
fish_color_end F0BC6E
fish_color_error E67E80
fish_color_param 9E9EC8
fish_color_comment 555555
fish_color_selection --background=2A2A2A
fish_color_search_match --background=2A2A2A
fish_color_operator 7A9E6E
fish_color_escape B87A9E
fish_color_autosuggestion 555555
fish_color_cancel E67E80 --reverse
fish_color_option F0BC6E
fish_color_history_current --bold
fish_color_status E67E80
fish_color_valid_path --underline
fish_color_cwd 7A9E6E
fish_color_cwd_root E67E80
fish_color_host 9E9EC8
fish_color_host_remote 9E9EC8
fish_color_user 6E9AB5
fish_pager_color_progress 555555
fish_pager_color_background
fish_pager_color_prefix 6E9AB5
fish_pager_color_completion E0E0E0
fish_pager_color_description 555555
fish_pager_color_selected_background --background=2A2A2A
fish_pager_color_selected_prefix 6E9AB5
fish_pager_color_selected_completion E0E0E0
fish_pager_color_selected_description 555555
fish_pager_color_secondary_background
fish_pager_color_secondary_prefix 6E9AB5
fish_pager_color_secondary_completion E0E0E0
fish_pager_color_secondary_description 555555
